### ISSUE TITLE
Use rake to generate docker files in out

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/bioc_docker#15]
From the README file, I understand that `rake devel_base` should use the *in* files in `src/base` and create the corresponding files in `out/base`. This fails however when I don't have anything already present in `out`. For example, when experimenting with an `mscore` image, I get
```
...
building devel_mscore from Dockerfile in out/devel_mscore...
...
```
and I can reproduce this if I remove any of the `src` directories for the existing images. What am I missing?

**Comment by lshep** [comment]
I'll look into changing the rake file to create directories if they aren't already created. Thank you for bringing this to my attention.

**Comment by lgatto** [comment]
I don't think it's only a matter of missing directory, as it still fails creating `out/devel_mscore`.

**Comment by lshep** [comment]
When I was playing around with adding the hooks directory it has some weird results as well until I fixed the directory structure but I will look into the rake file to see how we assemble the list of files to copy to see if it needs to be updated

**Comment by lshep** [comment]
Also if you are creating a new devel and release for mscore  did you add mscore to the config.yml under the containers section?

**Comment by lgatto** [comment]
> Also if you are creating a new devel and release for mscore did you add mscore to the config.yml under the containers section?

Yes -

```
containers: # FIXME (?) rename this to 'images' (?)
    base:
        parent: bogus
    core:
        parent: bioconductor/base
    mscore:
        parent: bioconductor/base
    protmetcore:
        parent: bioconductor/core
        biocViews:
            - Metabolomics
            - Proteomics
    metabolomics:
        parent: bioconductor/protmetcore
        biocViews:
            - Metabolomics
```
And the `src/mscore/*` files are basically copied from `src/core` with an update package list. I can `rake devel_mscore` when I copy and update the `out/devel_core/*` files to `out/devel_mscore/.`, otherwise it fails as shown above.
